version: 2

updates:
  - package-ecosystem: composer
    directory: /
    groups:
      php-minor-and-patch:
        patterns: ['*']
        update-types: [minor, patch]
    labels: [Dependencies, PHP]
    schedule:
      interval: monthly
    cooldown:
      default-days: 2
    assignees: [PHLAK]

  - package-ecosystem: npm
    directory: /
    groups:
      javascript-minor-and-patch:
        patterns: ['*']
        update-types: [minor, patch]
    labels: [Dependencies, JavaScript]
    schedule:
      interval: monthly
    cooldown:
      default-days: 2
    assignees: [PHLAK]

  - package-ecosystem: github-actions
    directory: /
    groups:
      github-actions-minor-and-patch:
        patterns: ['*']
        update-types: [minor, patch]
    labels: [Dependencies, GitHub Actions]
    schedule:
      interval: monthly
    cooldown:
      default-days: 2
    assignees: [PHLAK]
