preset: laravel

risky: false

enabled:
  - concat_with_spaces

disabled:
  - concat_without_spaces
  - post_increment
  - trailing_comma_in_multiline_array

finder:
  path:
    - "app"
    - "tests"
  name:
    - "*.php"
  exclude:
    - "app/cache"
    - "app/vendor"
